font_family      family="JetBrains Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
 font_size 12.0
scrollback_lines 5000
background_opacity 0.9
macos_titlebar_color background
include current-theme.conf
